// This file was generated by stubber; DO NOT EDIT

package app

import "net/http"

type StubbedFrobnicator struct {
	FrobnicateStub func(r *http.Request) ([]byte, error)
}

func (s *StubbedFrobnicator) Frobnicate(r *http.Request) ([]byte, error) {
	if s.FrobnicateStub == nil {
		panic("StubbedFrobnicator.Frobnicate: nil method stub")
	}
	return (s.FrobnicateStub)(r)
}

// Compile-time check that the implementation matches the interface.
var _ Frobnicator = (*StubbedFrobnicator)(nil)
