// This file was generated by stubber; DO NOT EDIT

package pkg

import "database/sql"

type StubbedSessionManager struct {
	GetUserIDStub  func(db *sql.DB, username string) (int64, error)
	getUserIDCalls []struct {
		Db       *sql.DB
		Username string
	}
}

func (s *StubbedSessionManager) GetUserID(db *sql.DB, username string) (int64, error) {
	if s.GetUserIDStub == nil {
		panic("StubbedSessionManager.GetUserID: nil method stub")
	}
	s.getUserIDCalls = append(s.getUserIDCalls, struct {
		Db       *sql.DB
		Username string
	}{Db: db, Username: username})
	return (s.GetUserIDStub)(db, username)
}

func (s *StubbedSessionManager) GetUserIDCalls() []struct {
	Db       *sql.DB
	Username string
} {
	return s.getUserIDCalls
}

// Compile-time check that the implementation matches the interface.
var _ SessionManager = (*StubbedSessionManager)(nil)
