// This file was generated by stubber; DO NOT EDIT

package pkg

import "database/sql"

// StubbedSessionManager is a stubbed implementation of SessionManager.
type StubbedSessionManager struct {
	// GetUserIDStub defines the implementation for GetUserID.
	GetUserIDStub  func(db *sql.DB, username string) (int64, error)
	getUserIDCalls []struct {
		Db       *sql.DB
		Username string
	}
}

// GetUserID delegates its behavior to the field GetUserIDStub.
func (s *StubbedSessionManager) GetUserID(db *sql.DB, username string) (int64, error) {
	if s.GetUserIDStub == nil {
		panic("StubbedSessionManager.GetUserID: nil method stub")
	}
	s.getUserIDCalls = append(s.getUserIDCalls, struct {
		Db       *sql.DB
		Username string
	}{Db: db, Username: username})
	return (s.GetUserIDStub)(db, username)
}

// GetUserIDCalls returns a slice of calls made to GetUserID. Each element
// of the slice represents the parameters that were provided.
func (s *StubbedSessionManager) GetUserIDCalls() []struct {
	Db       *sql.DB
	Username string
} {
	return s.getUserIDCalls
}

// Compile-time check that the implementation matches the interface.
var _ SessionManager = (*StubbedSessionManager)(nil)
