// This file was generated by stubber; DO NOT EDIT

// +build !nostubs

package stubs

import (
	"github.com/dradtke/stubber/testdata/bank"
	"io"
)

// Account is a stubbed implementation of bank.Account.
type Account struct {
	// BalanceStub defines the implementation for Balance.
	BalanceStub  func() int
	balanceCalls []struct{}
	// SummarizeStub defines the implementation for Summarize.
	SummarizeStub  func(w io.Writer)
	summarizeCalls []struct{ W io.Writer }
}

// Balance delegates its behavior to the field BalanceStub.
func (s *Account) Balance() int {
	if s.BalanceStub == nil {
		panic("Account.Balance: nil method stub")
	}
	s.balanceCalls = append(s.balanceCalls, struct{}{})
	return (s.BalanceStub)()
}

// BalanceCalls returns a slice of calls made to Balance. Each element
// of the slice represents the parameters that were provided.
func (s *Account) BalanceCalls() []struct{} {
	return s.balanceCalls
}

// Summarize delegates its behavior to the field SummarizeStub.
func (s *Account) Summarize(w io.Writer) {
	if s.SummarizeStub == nil {
		panic("Account.Summarize: nil method stub")
	}
	s.summarizeCalls = append(s.summarizeCalls, struct{ W io.Writer }{W: w})
	(s.SummarizeStub)(w)
}

// SummarizeCalls returns a slice of calls made to Summarize. Each element
// of the slice represents the parameters that were provided.
func (s *Account) SummarizeCalls() []struct{ W io.Writer } {
	return s.summarizeCalls
}

// Compile-time check that the implementation matches the interface.
var _ bank.Account = (*Account)(nil)

// WithdrawableAccount is a stubbed implementation of bank.WithdrawableAccount.
type WithdrawableAccount struct {
	// BalanceStub defines the implementation for Balance.
	BalanceStub  func() int
	balanceCalls []struct{}
	// SummarizeStub defines the implementation for Summarize.
	SummarizeStub  func(w io.Writer)
	summarizeCalls []struct{ W io.Writer }
	// WithdrawStub defines the implementation for Withdraw.
	WithdrawStub  func(amount int) (int, error)
	withdrawCalls []struct{ Amount int }
}

// Balance delegates its behavior to the field BalanceStub.
func (s *WithdrawableAccount) Balance() int {
	if s.BalanceStub == nil {
		panic("WithdrawableAccount.Balance: nil method stub")
	}
	s.balanceCalls = append(s.balanceCalls, struct{}{})
	return (s.BalanceStub)()
}

// BalanceCalls returns a slice of calls made to Balance. Each element
// of the slice represents the parameters that were provided.
func (s *WithdrawableAccount) BalanceCalls() []struct{} {
	return s.balanceCalls
}

// Summarize delegates its behavior to the field SummarizeStub.
func (s *WithdrawableAccount) Summarize(w io.Writer) {
	if s.SummarizeStub == nil {
		panic("WithdrawableAccount.Summarize: nil method stub")
	}
	s.summarizeCalls = append(s.summarizeCalls, struct{ W io.Writer }{W: w})
	(s.SummarizeStub)(w)
}

// SummarizeCalls returns a slice of calls made to Summarize. Each element
// of the slice represents the parameters that were provided.
func (s *WithdrawableAccount) SummarizeCalls() []struct{ W io.Writer } {
	return s.summarizeCalls
}

// Withdraw delegates its behavior to the field WithdrawStub.
func (s *WithdrawableAccount) Withdraw(amount int) (int, error) {
	if s.WithdrawStub == nil {
		panic("WithdrawableAccount.Withdraw: nil method stub")
	}
	s.withdrawCalls = append(s.withdrawCalls, struct{ Amount int }{Amount: amount})
	return (s.WithdrawStub)(amount)
}

// WithdrawCalls returns a slice of calls made to Withdraw. Each element
// of the slice represents the parameters that were provided.
func (s *WithdrawableAccount) WithdrawCalls() []struct{ Amount int } {
	return s.withdrawCalls
}

// Compile-time check that the implementation matches the interface.
var _ bank.WithdrawableAccount = (*WithdrawableAccount)(nil)
